server:
  port: 8080
  
spring:
  application:
    name: iso8583-annotation-processor
  
  webflux:
    base-path: /
    
logging:
  level:
    com.example.iso8583: DEBUG
    com.solab.iso8583: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/iso8583-processor.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configurações específicas da aplicação
app:
  iso8583:
    # Configuração totalmente programática - sem XML
    assign-date: true
    encoding: "UTF-8"
    use-binary-messages: false
    ignore-last-missing-field: true
